services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=postgres
      - DB_SCHEMA=public
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=12345
      - PG_DB=postgres
      - PG_PORT=5432
      - GOOGLE_RECAPTCHA_SECRET_KEY=6LfBauspAAAAALRPAwnqea2ckVmVxTuEEbj1Qfnf
      - JWT_SECRET=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis-db
    image: redis
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - 6379:6379
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - redis:/data

  postgres:
    container_name: postgres-db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
  redis:
    driver: local
